<template><div><h1 id="resources" tabindex="-1"><a class="header-anchor" href="#resources" aria-hidden="true">#</a> Resources</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>Resources directory is used to store all the files related to assets.</p>
<p>Let's say we want to use same delete icon from assets in 4 different places, so either we could use <code v-pre>asstes/icons/essentials/delete.svg</code> in all the 4 files saparatly or we can assign this path string to one variable in one saparate file and can access that variable in every file. Now if we restructure assets or rename the file, we will have to do the changes in one file only.</p>
<p>As of now we have <code v-pre>assets.dart</code> file in Resource directory</p>
<div class="language-dart line-numbers-mode" data-ext="dart"><pre v-pre class="language-dart"><code><span class="token keyword">class</span> <span class="token class-name">ImageAssets</span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> <span class="token class-name">ImageAssets</span><span class="token punctuation">.</span><span class="token function">_</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token comment">// General</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralBack <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/back.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralIconClose <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_close.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralError <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_error.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralExpand <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_expand.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralLocation <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_location.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralNoConnection <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_no_connection.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralRight <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_right.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralRadioNormal <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_radio_normal.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralRadioSelected <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_radio_selected.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralDelete <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/delete.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralVideo <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/video.svg'</span></span><span class="token punctuation">;</span>
  <span class="token keyword">static</span> <span class="token keyword">const</span> iconGeneralVideoPlayIcon <span class="token operator">=</span> <span class="token string-literal"><span class="token string">'assets/icons/general/icon_play_video.svg'</span></span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Developers can add simmilar files like this if needed (e.g. <code v-pre>project_assets.dart</code> for storing all project specific assets).</p>
</div></template>


