<template><div><h1 id="routes" tabindex="-1"><a class="header-anchor" href="#routes" aria-hidden="true">#</a> Routes</h1>
<nav class="table-of-contents"><ul></ul></nav>
<p>Routes is file which does path to Page(View) mapping. This routes are used in <RouterLink to="/vaahflutter/directory_structure/lib/routes/middleware.html">middleware</RouterLink> file.</p>
<div class="language-dart line-numbers-mode" data-ext="dart"><pre v-pre class="language-dart"><code><span class="token keyword">import</span> <span class="token string-literal"><span class="token string">'package:flutter/material.dart'</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token string-literal"><span class="token string">'package:example/view/pages/home.dart'</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token string-literal"><span class="token string">'package:example/view/pages/not_found.dart'</span></span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token string-literal"><span class="token string">'package:example/view/pages/permission_denied.dart'</span></span><span class="token punctuation">;</span>

<span class="token keyword">final</span> <span class="token class-name">Map</span><span class="token operator">&lt;</span><span class="token class-name">String</span><span class="token punctuation">,</span> <span class="token class-name">Route</span><span class="token generics"><span class="token punctuation">&lt;</span><span class="token keyword">dynamic</span><span class="token punctuation">></span></span> <span class="token class-name">Function</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">></span> routes <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token string-literal"><span class="token string">'/'</span></span><span class="token punctuation">:</span> <span class="token class-name">HomePage</span><span class="token punctuation">.</span>route<span class="token punctuation">,</span>
  <span class="token class-name">HomePage</span><span class="token punctuation">.</span>routePath<span class="token punctuation">:</span> <span class="token class-name">HomePage</span><span class="token punctuation">.</span>route<span class="token punctuation">,</span>
  <span class="token class-name">NotFoundPage</span><span class="token punctuation">.</span>routePath<span class="token punctuation">:</span> <span class="token class-name">NotFoundPage</span><span class="token punctuation">.</span>route<span class="token punctuation">,</span>
  <span class="token class-name">PermissionDeniedPage</span><span class="token punctuation">.</span>routePath<span class="token punctuation">:</span> <span class="token class-name">PermissionDeniedPage</span><span class="token punctuation">.</span>route<span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


