<template><div><h1 id="android" tabindex="-1"><a class="header-anchor" href="#android" aria-hidden="true">#</a> Android</h1>
<nav class="table-of-contents"><ul><li><router-link to="#what-is-this-directory-about">What is this directory about</router-link></li></ul></nav>
<h2 id="what-is-this-directory-about" tabindex="-1"><a class="header-anchor" href="#what-is-this-directory-about" aria-hidden="true">#</a> What is this directory about</h2>
<p>The Android folder contains files and folders required for running the application on an Android operating system. These files and folders are autogenerated during the creation of the flutter project. It’s recommended that these folders and files are left as is.</p>
<p>We modify this directory/files if we need to in some scenerios such as, adding flavors, adding store keys, etc.</p>
<p>The android folder’s primary sub-folders are the res folder and AndroidManifest.xml file. The res folder contains non-programmable resources required for the application, like icons, images, and fonts, while the AndroidManifest.xml file contains information needed by the application SDK.</p>
<p><code v-pre>build.gradle</code> in <code v-pre>android/app</code> It contains the <code v-pre>applicationId</code> that is required when submitting to Google Play Store. Make sure, this value matches the value you specify in Google Play Console before uploading your app. ❗ Be sure to check the path! There is another build.gradle file in the android subfolder.</p>
<p><code v-pre>AndroidManifest.xml</code> in <code v-pre>android/app/src/main</code> Here you can specify <code v-pre>intents</code> or <code v-pre>capabilities</code> that your app is going to use. When using 3rd party packages, their installation instructions usually include detailed information on what needs to be added here. ❗ Again be sure to check the path because there are other manifest files at <code v-pre>android/app/src/debug</code> and <code v-pre>android/app/src/profile</code>! if needed you edit <code v-pre>manifest</code> files from <code v-pre>debug</code> and <code v-pre>profile</code>.</p>
</div></template>


